// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestObect.proto

public final class TestObect {
  private TestObect() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TestObjectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TestObject)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 field1 = 1;</code>
     */
    int getField1();

    /**
     * <code>int32 field2 = 2;</code>
     */
    int getField2();

    /**
     * <code>int32 field3 = 3;</code>
     */
    int getField3();

    /**
     * <code>int32 field4 = 4;</code>
     */
    int getField4();

    /**
     * <code>int32 field5 = 5;</code>
     */
    int getField5();
  }
  /**
   * Protobuf type {@code TestObject}
   */
  public  static final class TestObject extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TestObject)
      TestObjectOrBuilder {
    // Use TestObject.newBuilder() to construct.
    private TestObject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TestObject() {
      field1_ = 0;
      field2_ = 0;
      field3_ = 0;
      field4_ = 0;
      field5_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TestObject(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              field1_ = input.readInt32();
              break;
            }
            case 16: {

              field2_ = input.readInt32();
              break;
            }
            case 24: {

              field3_ = input.readInt32();
              break;
            }
            case 32: {

              field4_ = input.readInt32();
              break;
            }
            case 40: {

              field5_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TestObect.internal_static_TestObject_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TestObect.internal_static_TestObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TestObect.TestObject.class, TestObect.TestObject.Builder.class);
    }

    public static final int FIELD1_FIELD_NUMBER = 1;
    private int field1_;
    /**
     * <code>int32 field1 = 1;</code>
     */
    public int getField1() {
      return field1_;
    }

    public static final int FIELD2_FIELD_NUMBER = 2;
    private int field2_;
    /**
     * <code>int32 field2 = 2;</code>
     */
    public int getField2() {
      return field2_;
    }

    public static final int FIELD3_FIELD_NUMBER = 3;
    private int field3_;
    /**
     * <code>int32 field3 = 3;</code>
     */
    public int getField3() {
      return field3_;
    }

    public static final int FIELD4_FIELD_NUMBER = 4;
    private int field4_;
    /**
     * <code>int32 field4 = 4;</code>
     */
    public int getField4() {
      return field4_;
    }

    public static final int FIELD5_FIELD_NUMBER = 5;
    private int field5_;
    /**
     * <code>int32 field5 = 5;</code>
     */
    public int getField5() {
      return field5_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (field1_ != 0) {
        output.writeInt32(1, field1_);
      }
      if (field2_ != 0) {
        output.writeInt32(2, field2_);
      }
      if (field3_ != 0) {
        output.writeInt32(3, field3_);
      }
      if (field4_ != 0) {
        output.writeInt32(4, field4_);
      }
      if (field5_ != 0) {
        output.writeInt32(5, field5_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (field1_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, field1_);
      }
      if (field2_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, field2_);
      }
      if (field3_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, field3_);
      }
      if (field4_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, field4_);
      }
      if (field5_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, field5_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TestObect.TestObject)) {
        return super.equals(obj);
      }
      TestObect.TestObject other = (TestObect.TestObject) obj;

      boolean result = true;
      result = result && (getField1()
          == other.getField1());
      result = result && (getField2()
          == other.getField2());
      result = result && (getField3()
          == other.getField3());
      result = result && (getField4()
          == other.getField4());
      result = result && (getField5()
          == other.getField5());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FIELD1_FIELD_NUMBER;
      hash = (53 * hash) + getField1();
      hash = (37 * hash) + FIELD2_FIELD_NUMBER;
      hash = (53 * hash) + getField2();
      hash = (37 * hash) + FIELD3_FIELD_NUMBER;
      hash = (53 * hash) + getField3();
      hash = (37 * hash) + FIELD4_FIELD_NUMBER;
      hash = (53 * hash) + getField4();
      hash = (37 * hash) + FIELD5_FIELD_NUMBER;
      hash = (53 * hash) + getField5();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TestObect.TestObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TestObect.TestObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TestObect.TestObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TestObect.TestObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TestObect.TestObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TestObect.TestObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TestObect.TestObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TestObect.TestObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TestObect.TestObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TestObect.TestObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TestObect.TestObject prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TestObject}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TestObject)
        TestObect.TestObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TestObect.internal_static_TestObject_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TestObect.internal_static_TestObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TestObect.TestObject.class, TestObect.TestObject.Builder.class);
      }

      // Construct using TestObect.TestObject.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        field1_ = 0;

        field2_ = 0;

        field3_ = 0;

        field4_ = 0;

        field5_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TestObect.internal_static_TestObject_descriptor;
      }

      public TestObect.TestObject getDefaultInstanceForType() {
        return TestObect.TestObject.getDefaultInstance();
      }

      public TestObect.TestObject build() {
        TestObect.TestObject result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TestObect.TestObject buildPartial() {
        TestObect.TestObject result = new TestObect.TestObject(this);
        result.field1_ = field1_;
        result.field2_ = field2_;
        result.field3_ = field3_;
        result.field4_ = field4_;
        result.field5_ = field5_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TestObect.TestObject) {
          return mergeFrom((TestObect.TestObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TestObect.TestObject other) {
        if (other == TestObect.TestObject.getDefaultInstance()) return this;
        if (other.getField1() != 0) {
          setField1(other.getField1());
        }
        if (other.getField2() != 0) {
          setField2(other.getField2());
        }
        if (other.getField3() != 0) {
          setField3(other.getField3());
        }
        if (other.getField4() != 0) {
          setField4(other.getField4());
        }
        if (other.getField5() != 0) {
          setField5(other.getField5());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TestObect.TestObject parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TestObect.TestObject) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int field1_ ;
      /**
       * <code>int32 field1 = 1;</code>
       */
      public int getField1() {
        return field1_;
      }
      /**
       * <code>int32 field1 = 1;</code>
       */
      public Builder setField1(int value) {
        
        field1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 field1 = 1;</code>
       */
      public Builder clearField1() {
        
        field1_ = 0;
        onChanged();
        return this;
      }

      private int field2_ ;
      /**
       * <code>int32 field2 = 2;</code>
       */
      public int getField2() {
        return field2_;
      }
      /**
       * <code>int32 field2 = 2;</code>
       */
      public Builder setField2(int value) {
        
        field2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 field2 = 2;</code>
       */
      public Builder clearField2() {
        
        field2_ = 0;
        onChanged();
        return this;
      }

      private int field3_ ;
      /**
       * <code>int32 field3 = 3;</code>
       */
      public int getField3() {
        return field3_;
      }
      /**
       * <code>int32 field3 = 3;</code>
       */
      public Builder setField3(int value) {
        
        field3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 field3 = 3;</code>
       */
      public Builder clearField3() {
        
        field3_ = 0;
        onChanged();
        return this;
      }

      private int field4_ ;
      /**
       * <code>int32 field4 = 4;</code>
       */
      public int getField4() {
        return field4_;
      }
      /**
       * <code>int32 field4 = 4;</code>
       */
      public Builder setField4(int value) {
        
        field4_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 field4 = 4;</code>
       */
      public Builder clearField4() {
        
        field4_ = 0;
        onChanged();
        return this;
      }

      private int field5_ ;
      /**
       * <code>int32 field5 = 5;</code>
       */
      public int getField5() {
        return field5_;
      }
      /**
       * <code>int32 field5 = 5;</code>
       */
      public Builder setField5(int value) {
        
        field5_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 field5 = 5;</code>
       */
      public Builder clearField5() {
        
        field5_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:TestObject)
    }

    // @@protoc_insertion_point(class_scope:TestObject)
    private static final TestObect.TestObject DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TestObect.TestObject();
    }

    public static TestObect.TestObject getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TestObject>
        PARSER = new com.google.protobuf.AbstractParser<TestObject>() {
      public TestObject parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TestObject(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TestObject> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestObject> getParserForType() {
      return PARSER;
    }

    public TestObect.TestObject getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TestObject_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TestObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017TestObect.proto\"\\\n\nTestObject\022\016\n\006field" +
      "1\030\001 \001(\005\022\016\n\006field2\030\002 \001(\005\022\016\n\006field3\030\003 \001(\005\022" +
      "\016\n\006field4\030\004 \001(\005\022\016\n\006field5\030\005 \001(\005b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TestObject_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TestObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TestObject_descriptor,
        new java.lang.String[] { "Field1", "Field2", "Field3", "Field4", "Field5", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
